services:
  db:
    image: postgres:15
    container_name: isa_postgres_db
    environment:
      POSTGRES_USER: isa_user
      POSTGRES_PASSWORD: isa_password
      POSTGRES_DB: isa_bonus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: isa_redis

  bonus_service:
    build: ./microservices/bonus_service
    container_name: isa_bonus_service
    ports:
      - "8002:8000"
    volumes:
      - ./microservices/bonus_service:/app
    environment:
      DATABASE_URL: postgresql://isa_user:isa_password@db:5432/isa_bonus_db
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  worker_bonos:
    build: ./microservices/bonus_service
    container_name: isa_worker_bonos
    command: celery -A tasks worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://isa_user:isa_password@db:5432/isa_bonus_db
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  # ESTA ES LA PIEZA QUE FALTABA PARA EL SEGUNDO SERVICIO
  audit_service:
    build: ./microservices/audit_service
    container_name: isa_audit_service
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: postgresql://isa_user:isa_password@db:5432/isa_bonus_db
    depends_on:
      - db

volumes:
  postgres_data: