# prometheus/prometheus.yml
global:
  scrape_interval: 15s

# Conexión con Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Cargar las reglas que creamos en el Paso 1
rule_files:
  - "/etc/prometheus/alerts.yml"

# ¿A quién vamos a vigilar?
scrape_configs:
  - job_name: "reports_api"
    static_configs:
      # Apunta al nombre del contenedor de FastAPI y su puerto
      - targets: ["reports_service:8003"]