# Generated by Django 5.0.4 on 2026-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonos',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('salario_base_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impacto_ebitda_logrado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('performance_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_final_bono', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_calculo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bonos',
                'managed': False,
            },
        ),
    ]
