# Generated by Django 4.2.30 on 2026-06-10 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoEmpleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos_asignados', to='users.usuarios')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonos_evaluados', to='users.usuarios')),
            ],
            options={
                'verbose_name': 'Empleado en Bono',
                'verbose_name_plural': 'Empleados en Bonos',
                'db_table': 'bonos_empleados',
            },
        ),
        migrations.CreateModel(
            name='BonoMetasVinculadas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('meta', models.CharField(help_text='Ej: 99.9%, 1, 4.5/5', max_length=100)),
                ('actual', models.CharField(help_text='Valor actual alcanzado', max_length=100)),
                ('icono', models.CharField(choices=[('🖥️', '🖥️ Servidor/Infraestructura'), ('📜', '📜 Certificación'), ('🤝', '🤝 Equipo/Feedback'), ('📈', '📈 Ventas/Metas'), ('🎯', '🎯 Objetivo General')], default='🎯', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meta Vinculada',
                'verbose_name_plural': 'Metas Vinculadas',
                'db_table': 'bonos_metas_vinculadas',
            },
        ),
        migrations.CreateModel(
            name='BonoPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodo', models.CharField(help_text='Ej: Q1 2024, Q2 2024, etc.', max_length=50)),
                ('fecha_pago', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos_pagos', to='users.usuarios')),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finances.bonoempleado')),
            ],
            options={
                'verbose_name': 'Pago de Bono',
                'verbose_name_plural': 'Pagos de Bonos',
                'db_table': 'bonos_pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='BonoPrograma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_calculo', models.CharField(choices=[('porcentaje_salario', 'Porcentaje Salario Base'), ('monto_fijo', 'Monto Fijo')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej: 15.00) o monto fijo', max_digits=10)),
                ('presupuesto_limite', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('planeado', 'Planeado'), ('finalizado', 'Finalizado'), ('pausado', 'Pausado')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa de Bono',
                'verbose_name_plural': 'Programas de Bonos',
                'db_table': 'bonos_programas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='Bonos',
        ),
        migrations.AddField(
            model_name='bonopago',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finances.bonoprograma'),
        ),
        migrations.AddField(
            model_name='bonometasvinculadas',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_vinculadas', to='finances.bonoprograma'),
        ),
        migrations.AddField(
            model_name='bonoempleado',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_asignados', to='finances.bonoprograma'),
        ),
        migrations.AlterUniqueTogether(
            name='bonoempleado',
            unique_together={('programa', 'empleado')},
        ),
    ]
