# Generated by Django 5.0.4 on 2026-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprobaciones',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('firma_digital_base64', models.TextField()),
                ('ip_address', models.CharField(max_length=45)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aprobaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialEstados',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=50)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogsSistema',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=45)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logs_sistema',
                'managed': False,
            },
        ),
    ]
